"""add animals table

Revision ID: 7c9c5e826da0
Revises: 
Create Date: 2024-02-18 08:01:20.100773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c9c5e826da0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
#     with op.batch_alter_table('employees', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.BIGINT(),
#                server_default=None,
#                type_=sa.Integer(),
#                existing_nullable=False,
#                autoincrement=True)
#         batch_op.alter_column('gender',
#                existing_type=sa.TEXT(),
#                type_=sa.String(length=100),
#                existing_nullable=True)
#         batch_op.alter_column('phone',
#                existing_type=sa.BIGINT(),
#                type_=sa.Integer(),
#                existing_nullable=True)
#         batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.alter_column('phone',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    op.drop_table('animals')
    # ### end Alembic commands ###
